// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: crawler.proto

package server

import (
	"context"

	"crawler/internal/logic"
	"crawler/internal/svc"
	"crawler/proto"
)

type CrawlerServiceServer struct {
	svcCtx *svc.ServiceContext
	proto.UnimplementedCrawlerServiceServer
}

func NewCrawlerServiceServer(svcCtx *svc.ServiceContext) *CrawlerServiceServer {
	return &CrawlerServiceServer{
		svcCtx: svcCtx,
	}
}

// 启动爬虫任务
func (s *CrawlerServiceServer) StartCrawl(ctx context.Context, in *proto.CrawlRequest) (*proto.CrawlResponse, error) {
	l := logic.NewStartCrawlLogic(ctx, s.svcCtx)
	return l.StartCrawl(in)
}

// 获取爬虫任务状态
func (s *CrawlerServiceServer) GetCrawlStatus(ctx context.Context, in *proto.StatusRequest) (*proto.StatusResponse, error) {
	l := logic.NewGetCrawlStatusLogic(ctx, s.svcCtx)
	return l.GetCrawlStatus(in)
}

// 获取已爬取的数据
func (s *CrawlerServiceServer) GetCrawledData(ctx context.Context, in *proto.DataRequest) (*proto.DataResponse, error) {
	l := logic.NewGetCrawledDataLogic(ctx, s.svcCtx)
	return l.GetCrawledData(in)
}
