# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: crawler.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'crawler.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rcrawler.proto\x12\x07\x63rawler\"\xcb\x01\n\x0c\x43rawlRequest\x12\x1b\n\x04site\x18\x01 \x01(\x0e\x32\r.crawler.Site\x12\x0f\n\x07keyword\x18\x02 \x01(\t\x12\x12\n\npost_count\x18\x03 \x01(\x04\x12\x11\n\tmin_likes\x18\x04 \x01(\x04\x12\x19\n\x11\x63omment_min_likes\x18\x05 \x01(\x04\x12\x19\n\x11\x63omments_per_post\x18\x06 \x01(\x04\x12\x18\n\x10include_comments\x18\x07 \x01(\x08\x12\x16\n\x0einclude_images\x18\x08 \x01(\x08\"B\n\rCrawlResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t*\x17\n\x04Site\x12\x0f\n\x0bXIAOHONGSHU\x10\x00\x32M\n\x0e\x43rawlerService\x12;\n\nStartCrawl\x12\x15.crawler.CrawlRequest\x1a\x16.crawler.CrawlResponseB\tZ\x07./protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'crawler_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'Z\007./proto'
    _globals['_SITE']._serialized_start = 300
    _globals['_SITE']._serialized_end = 323
    _globals['_CRAWLREQUEST']._serialized_start = 27
    _globals['_CRAWLREQUEST']._serialized_end = 230
    _globals['_CRAWLRESPONSE']._serialized_start = 232
    _globals['_CRAWLRESPONSE']._serialized_end = 298
    _globals['_CRAWLERSERVICE']._serialized_start = 325
    _globals['_CRAWLERSERVICE']._serialized_end = 402
# @@protoc_insertion_point(module_scope)
