# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import crawler_pb2 as crawler__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in crawler_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CrawlerServiceStub(object):
    """爬虫服务定义
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartCrawl = channel.unary_unary(
                '/crawler.CrawlerService/StartCrawl',
                request_serializer=crawler__pb2.CrawlRequest.SerializeToString,
                response_deserializer=crawler__pb2.CrawlResponse.FromString,
                _registered_method=True)
        self.GetCrawlStatus = channel.unary_unary(
                '/crawler.CrawlerService/GetCrawlStatus',
                request_serializer=crawler__pb2.StatusRequest.SerializeToString,
                response_deserializer=crawler__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetCrawledData = channel.unary_unary(
                '/crawler.CrawlerService/GetCrawledData',
                request_serializer=crawler__pb2.DataRequest.SerializeToString,
                response_deserializer=crawler__pb2.DataResponse.FromString,
                _registered_method=True)


class CrawlerServiceServicer(object):
    """爬虫服务定义
    """

    def StartCrawl(self, request, context):
        """启动爬虫任务
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCrawlStatus(self, request, context):
        """获取爬虫任务状态
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCrawledData(self, request, context):
        """获取已爬取的数据
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CrawlerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartCrawl': grpc.unary_unary_rpc_method_handler(
                    servicer.StartCrawl,
                    request_deserializer=crawler__pb2.CrawlRequest.FromString,
                    response_serializer=crawler__pb2.CrawlResponse.SerializeToString,
            ),
            'GetCrawlStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCrawlStatus,
                    request_deserializer=crawler__pb2.StatusRequest.FromString,
                    response_serializer=crawler__pb2.StatusResponse.SerializeToString,
            ),
            'GetCrawledData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCrawledData,
                    request_deserializer=crawler__pb2.DataRequest.FromString,
                    response_serializer=crawler__pb2.DataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'crawler.CrawlerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('crawler.CrawlerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CrawlerService(object):
    """爬虫服务定义
    """

    @staticmethod
    def StartCrawl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crawler.CrawlerService/StartCrawl',
            crawler__pb2.CrawlRequest.SerializeToString,
            crawler__pb2.CrawlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCrawlStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crawler.CrawlerService/GetCrawlStatus',
            crawler__pb2.StatusRequest.SerializeToString,
            crawler__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCrawledData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crawler.CrawlerService/GetCrawledData',
            crawler__pb2.DataRequest.SerializeToString,
            crawler__pb2.DataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
