// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: crawler.proto

package crawlerservice

import (
	"context"

	"crawler/proto"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Comment       = proto.Comment
	CrawlRequest  = proto.CrawlRequest
	CrawlResponse = proto.CrawlResponse
	PostItem      = proto.PostItem

	CrawlerService interface {
		// 启动爬虫任务
		StartCrawl(ctx context.Context, in *CrawlRequest, opts ...grpc.CallOption) (*CrawlResponse, error)
	}

	defaultCrawlerService struct {
		cli zrpc.Client
	}
)

func NewCrawlerService(cli zrpc.Client) CrawlerService {
	return &defaultCrawlerService{
		cli: cli,
	}
}

// 启动爬虫任务
func (m *defaultCrawlerService) StartCrawl(ctx context.Context, in *CrawlRequest, opts ...grpc.CallOption) (*CrawlResponse, error) {
	client := proto.NewCrawlerServiceClient(m.cli.Conn())
	return client.StartCrawl(ctx, in, opts...)
}
