// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: crawler.proto

package crawlerservice

import (
	"context"

	"crawler/proto"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Comment        = proto.Comment
	CrawlRequest   = proto.CrawlRequest
	CrawlResponse  = proto.CrawlResponse
	DataRequest    = proto.DataRequest
	DataResponse   = proto.DataResponse
	PostItem       = proto.PostItem
	StatusRequest  = proto.StatusRequest
	StatusResponse = proto.StatusResponse

	CrawlerService interface {
		// 启动爬虫任务
		StartCrawl(ctx context.Context, in *CrawlRequest, opts ...grpc.CallOption) (*CrawlResponse, error)
		// 获取爬虫任务状态
		GetCrawlStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
		// 获取已爬取的数据
		GetCrawledData(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (*DataResponse, error)
	}

	defaultCrawlerService struct {
		cli zrpc.Client
	}
)

func NewCrawlerService(cli zrpc.Client) CrawlerService {
	return &defaultCrawlerService{
		cli: cli,
	}
}

// 启动爬虫任务
func (m *defaultCrawlerService) StartCrawl(ctx context.Context, in *CrawlRequest, opts ...grpc.CallOption) (*CrawlResponse, error) {
	client := proto.NewCrawlerServiceClient(m.cli.Conn())
	return client.StartCrawl(ctx, in, opts...)
}

// 获取爬虫任务状态
func (m *defaultCrawlerService) GetCrawlStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	client := proto.NewCrawlerServiceClient(m.cli.Conn())
	return client.GetCrawlStatus(ctx, in, opts...)
}

// 获取已爬取的数据
func (m *defaultCrawlerService) GetCrawledData(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (*DataResponse, error) {
	client := proto.NewCrawlerServiceClient(m.cli.Conn())
	return client.GetCrawledData(ctx, in, opts...)
}
