// Code generated by MockGen. DO NOT EDIT.
// Source: taskqueue.go
//
// Generated by this command:
//
//	mockgen -source=taskqueue.go -destination=./mock/taskqueue_mock.go -package=queue
//

// Package queue is a generated GoMock package.
package queue

import (
	proto "crawler/proto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTaskQueue is a mock of TaskQueue interface.
type MockTaskQueue struct {
	ctrl     *gomock.Controller
	recorder *MockTaskQueueMockRecorder
	isgomock struct{}
}

// MockTaskQueueMockRecorder is the mock recorder for MockTaskQueue.
type MockTaskQueueMockRecorder struct {
	mock *MockTaskQueue
}

// NewMockTaskQueue creates a new mock instance.
func NewMockTaskQueue(ctrl *gomock.Controller) *MockTaskQueue {
	mock := &MockTaskQueue{ctrl: ctrl}
	mock.recorder = &MockTaskQueueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskQueue) EXPECT() *MockTaskQueueMockRecorder {
	return m.recorder
}

// AddTask mocks base method.
func (m *MockTaskQueue) AddTask(request *proto.CrawlRequest) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTask", request)
	ret0, _ := ret[0].(string)
	return ret0
}

// AddTask indicates an expected call of AddTask.
func (mr *MockTaskQueueMockRecorder) AddTask(request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTask", reflect.TypeOf((*MockTaskQueue)(nil).AddTask), request)
}

// AddTaskResult mocks base method.
func (m *MockTaskQueue) AddTaskResult(taskID string, items []*proto.PostItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTaskResult", taskID, items)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTaskResult indicates an expected call of AddTaskResult.
func (mr *MockTaskQueueMockRecorder) AddTaskResult(taskID, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTaskResult", reflect.TypeOf((*MockTaskQueue)(nil).AddTaskResult), taskID, items)
}

// GetTaskData mocks base method.
func (m *MockTaskQueue) GetTaskData(taskID string, offset, limit int32) (*proto.DataResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskData", taskID, offset, limit)
	ret0, _ := ret[0].(*proto.DataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskData indicates an expected call of GetTaskData.
func (mr *MockTaskQueueMockRecorder) GetTaskData(taskID, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskData", reflect.TypeOf((*MockTaskQueue)(nil).GetTaskData), taskID, offset, limit)
}

// GetTaskStatus mocks base method.
func (m *MockTaskQueue) GetTaskStatus(taskID string) (*proto.StatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskStatus", taskID)
	ret0, _ := ret[0].(*proto.StatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskStatus indicates an expected call of GetTaskStatus.
func (mr *MockTaskQueueMockRecorder) GetTaskStatus(taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskStatus", reflect.TypeOf((*MockTaskQueue)(nil).GetTaskStatus), taskID)
}

// Start mocks base method.
func (m *MockTaskQueue) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start.
func (mr *MockTaskQueueMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockTaskQueue)(nil).Start))
}

// Stop mocks base method.
func (m *MockTaskQueue) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockTaskQueueMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockTaskQueue)(nil).Stop))
}

// UpdateProgress mocks base method.
func (m *MockTaskQueue) UpdateProgress(taskID string, progress float32, itemsCollected int32) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateProgress", taskID, progress, itemsCollected)
}

// UpdateProgress indicates an expected call of UpdateProgress.
func (mr *MockTaskQueueMockRecorder) UpdateProgress(taskID, progress, itemsCollected any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProgress", reflect.TypeOf((*MockTaskQueue)(nil).UpdateProgress), taskID, progress, itemsCollected)
}
