// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0--rc2
// source: shared/protos/crawler.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 选取爬取站点
type Site int32

const (
	Site_XIAOHONGSHU Site = 0 //xiaohongshu
)

// Enum value maps for Site.
var (
	Site_name = map[int32]string{
		0: "XIAOHONGSHU",
	}
	Site_value = map[string]int32{
		"XIAOHONGSHU": 0,
	}
)

func (x Site) Enum() *Site {
	p := new(Site)
	*p = x
	return p
}

func (x Site) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Site) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_protos_crawler_proto_enumTypes[0].Descriptor()
}

func (Site) Type() protoreflect.EnumType {
	return &file_shared_protos_crawler_proto_enumTypes[0]
}

func (x Site) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Site.Descriptor instead.
func (Site) EnumDescriptor() ([]byte, []int) {
	return file_shared_protos_crawler_proto_rawDescGZIP(), []int{0}
}

// 爬虫请求参数
type CrawlRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Site            Site                   `protobuf:"varint,1,opt,name=site,proto3,enum=crawler.Site" json:"site,omitempty"`                              //爬取站点
	Keyword         string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`                                           // 搜索关键词，例如"南昌"
	PostCount       uint64                 `protobuf:"varint,3,opt,name=post_count,json=postCount,proto3" json:"post_count,omitempty"`                     // 爬取帖子数量
	MinLikes        uint64                 `protobuf:"varint,4,opt,name=min_likes,json=minLikes,proto3" json:"min_likes,omitempty"`                        // 最少点赞数筛选
	CommentMinLikes uint64                 `protobuf:"varint,5,opt,name=comment_min_likes,json=commentMinLikes,proto3" json:"comment_min_likes,omitempty"` // 每条评论爬取的回复数量
	CommentsPerPost uint64                 `protobuf:"varint,6,opt,name=comments_per_post,json=commentsPerPost,proto3" json:"comments_per_post,omitempty"` // 每个帖子爬取的评论数量
	IncludeComments bool                   `protobuf:"varint,7,opt,name=include_comments,json=includeComments,proto3" json:"include_comments,omitempty"`   // 是否包含评论
	IncludeImages   bool                   `protobuf:"varint,8,opt,name=include_images,json=includeImages,proto3" json:"include_images,omitempty"`         // 是否爬取图片URL
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CrawlRequest) Reset() {
	*x = CrawlRequest{}
	mi := &file_shared_protos_crawler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrawlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlRequest) ProtoMessage() {}

func (x *CrawlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protos_crawler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawlRequest.ProtoReflect.Descriptor instead.
func (*CrawlRequest) Descriptor() ([]byte, []int) {
	return file_shared_protos_crawler_proto_rawDescGZIP(), []int{0}
}

func (x *CrawlRequest) GetSite() Site {
	if x != nil {
		return x.Site
	}
	return Site_XIAOHONGSHU
}

func (x *CrawlRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *CrawlRequest) GetPostCount() uint64 {
	if x != nil {
		return x.PostCount
	}
	return 0
}

func (x *CrawlRequest) GetMinLikes() uint64 {
	if x != nil {
		return x.MinLikes
	}
	return 0
}

func (x *CrawlRequest) GetCommentMinLikes() uint64 {
	if x != nil {
		return x.CommentMinLikes
	}
	return 0
}

func (x *CrawlRequest) GetCommentsPerPost() uint64 {
	if x != nil {
		return x.CommentsPerPost
	}
	return 0
}

func (x *CrawlRequest) GetIncludeComments() bool {
	if x != nil {
		return x.IncludeComments
	}
	return false
}

func (x *CrawlRequest) GetIncludeImages() bool {
	if x != nil {
		return x.IncludeImages
	}
	return false
}

// 爬虫响应
type CrawlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // 任务ID，用于后续查询状态
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`            // 任务是否成功启动
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`             // 相关信息或错误消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrawlResponse) Reset() {
	*x = CrawlResponse{}
	mi := &file_shared_protos_crawler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrawlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlResponse) ProtoMessage() {}

func (x *CrawlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protos_crawler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawlResponse.ProtoReflect.Descriptor instead.
func (*CrawlResponse) Descriptor() ([]byte, []int) {
	return file_shared_protos_crawler_proto_rawDescGZIP(), []int{1}
}

func (x *CrawlResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CrawlResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CrawlResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_shared_protos_crawler_proto protoreflect.FileDescriptor

const file_shared_protos_crawler_proto_rawDesc = "" +
	"\n" +
	"\x1bshared/protos/crawler.proto\x12\acrawler\"\xb1\x02\n" +
	"\fCrawlRequest\x12!\n" +
	"\x04site\x18\x01 \x01(\x0e2\r.crawler.SiteR\x04site\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\x12\x1d\n" +
	"\n" +
	"post_count\x18\x03 \x01(\x04R\tpostCount\x12\x1b\n" +
	"\tmin_likes\x18\x04 \x01(\x04R\bminLikes\x12*\n" +
	"\x11comment_min_likes\x18\x05 \x01(\x04R\x0fcommentMinLikes\x12*\n" +
	"\x11comments_per_post\x18\x06 \x01(\x04R\x0fcommentsPerPost\x12)\n" +
	"\x10include_comments\x18\a \x01(\bR\x0fincludeComments\x12%\n" +
	"\x0einclude_images\x18\b \x01(\bR\rincludeImages\"\\\n" +
	"\rCrawlResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage*\x17\n" +
	"\x04Site\x12\x0f\n" +
	"\vXIAOHONGSHU\x10\x002M\n" +
	"\x0eCrawlerService\x12;\n" +
	"\n" +
	"StartCrawl\x12\x15.crawler.CrawlRequest\x1a\x16.crawler.CrawlResponseB\tZ\a./protob\x06proto3"

var (
	file_shared_protos_crawler_proto_rawDescOnce sync.Once
	file_shared_protos_crawler_proto_rawDescData []byte
)

func file_shared_protos_crawler_proto_rawDescGZIP() []byte {
	file_shared_protos_crawler_proto_rawDescOnce.Do(func() {
		file_shared_protos_crawler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_protos_crawler_proto_rawDesc), len(file_shared_protos_crawler_proto_rawDesc)))
	})
	return file_shared_protos_crawler_proto_rawDescData
}

var file_shared_protos_crawler_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shared_protos_crawler_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shared_protos_crawler_proto_goTypes = []any{
	(Site)(0),             // 0: crawler.Site
	(*CrawlRequest)(nil),  // 1: crawler.CrawlRequest
	(*CrawlResponse)(nil), // 2: crawler.CrawlResponse
}
var file_shared_protos_crawler_proto_depIdxs = []int32{
	0, // 0: crawler.CrawlRequest.site:type_name -> crawler.Site
	1, // 1: crawler.CrawlerService.StartCrawl:input_type -> crawler.CrawlRequest
	2, // 2: crawler.CrawlerService.StartCrawl:output_type -> crawler.CrawlResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shared_protos_crawler_proto_init() }
func file_shared_protos_crawler_proto_init() {
	if File_shared_protos_crawler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_protos_crawler_proto_rawDesc), len(file_shared_protos_crawler_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_protos_crawler_proto_goTypes,
		DependencyIndexes: file_shared_protos_crawler_proto_depIdxs,
		EnumInfos:         file_shared_protos_crawler_proto_enumTypes,
		MessageInfos:      file_shared_protos_crawler_proto_msgTypes,
	}.Build()
	File_shared_protos_crawler_proto = out.File
	file_shared_protos_crawler_proto_goTypes = nil
	file_shared_protos_crawler_proto_depIdxs = nil
}
